<?php

namespace Database\Seeders;

use App\Models\SubscriptionPlan;
use Illuminate\Database\Seeder;

class SubscriptionPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Free (Trial)',
                'slug' => 'free',
                'description' => 'Paket trial gratis untuk memulai. Cocok untuk ISP yang ingin mencoba layanan kami.',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'max_routers' => 1,
                'max_users' => 25,
                'max_vouchers' => 50,
                'max_online_users' => 5,
                'custom_domain' => false,
                'api_access' => false,
                'priority_support' => false,
                'features' => [
                    'basic_radius' => true,
                    'basic_reports' => true,
                    'pppoe' => false,
                    'hotspot' => false,
                    'sms_notification' => false,
                    'email_notification' => false,
                    'advanced_reports' => false,
                    'voucher_templates' => false,
                    'multi_location' => false,
                    'reseller_module' => false,
                    'advanced_analytics' => false,
                    'white_label' => false,
                    'sla' => false,
                    'dedicated_support' => false,
                    'custom_development' => false,
                    'on_premise' => false,
                    'support_type' => 'community',
                ],
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'description' => 'Paket pemula untuk ISP kecil yang baru memulai bisnis.',
                'price_monthly' => 99000,
                'price_yearly' => 990000,
                'max_routers' => 2,
                'max_users' => 100,
                'max_vouchers' => 500,
                'max_online_users' => 25,
                'custom_domain' => false,
                'api_access' => false,
                'priority_support' => false,
                'features' => [
                    'basic_radius' => true,
                    'basic_reports' => true,
                    'pppoe' => true,
                    'hotspot' => true,
                    'sms_notification' => false,
                    'email_notification' => false,
                    'advanced_reports' => false,
                    'voucher_templates' => false,
                    'multi_location' => false,
                    'reseller_module' => false,
                    'advanced_analytics' => false,
                    'white_label' => false,
                    'sla' => false,
                    'dedicated_support' => false,
                    'custom_development' => false,
                    'on_premise' => false,
                    'support_type' => 'community',
                ],
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Basic',
                'slug' => 'basic',
                'description' => 'Paket dasar dengan fitur essential untuk ISP kecil-menengah.',
                'price_monthly' => 199000,
                'price_yearly' => 1990000,
                'max_routers' => 5,
                'max_users' => 250,
                'max_vouchers' => 2500,
                'max_online_users' => 50,
                'custom_domain' => false,
                'api_access' => false,
                'priority_support' => false,
                'features' => [
                    'basic_radius' => true,
                    'basic_reports' => true,
                    'pppoe' => true,
                    'hotspot' => true,
                    'sms_notification' => true,
                    'email_notification' => false,
                    'advanced_reports' => false,
                    'voucher_templates' => false,
                    'multi_location' => false,
                    'reseller_module' => false,
                    'advanced_analytics' => false,
                    'white_label' => false,
                    'sla' => false,
                    'dedicated_support' => false,
                    'custom_development' => false,
                    'on_premise' => false,
                    'support_type' => 'email',
                ],
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Professional',
                'slug' => 'professional',
                'description' => 'Paket profesional dengan fitur lengkap untuk ISP menengah.',
                'price_monthly' => 399000,
                'price_yearly' => 3990000,
                'max_routers' => 15,
                'max_users' => 1000,
                'max_vouchers' => 10000,
                'max_online_users' => 200,
                'custom_domain' => true,
                'api_access' => true,
                'priority_support' => true,
                'features' => [
                    'basic_radius' => true,
                    'full_radius' => true,
                    'basic_reports' => true,
                    'advanced_reports' => true,
                    'pppoe' => true,
                    'hotspot' => true,
                    'sms_notification' => true,
                    'email_notification' => true,
                    'voucher_templates' => true,
                    'multi_location' => false,
                    'reseller_module' => false,
                    'advanced_analytics' => false,
                    'white_label' => false,
                    'sla' => false,
                    'dedicated_support' => false,
                    'custom_development' => false,
                    'on_premise' => false,
                    'support_type' => 'priority',
                ],
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Business',
                'slug' => 'business',
                'description' => 'Paket bisnis untuk ISP besar dengan fitur multi-lokasi dan reseller.',
                'price_monthly' => 799000,
                'price_yearly' => 7990000,
                'max_routers' => 50,
                'max_users' => 5000,
                'max_vouchers' => 50000,
                'max_online_users' => 1000,
                'custom_domain' => true,
                'api_access' => true,
                'priority_support' => true,
                'features' => [
                    'basic_radius' => true,
                    'full_radius' => true,
                    'basic_reports' => true,
                    'advanced_reports' => true,
                    'pppoe' => true,
                    'hotspot' => true,
                    'sms_notification' => true,
                    'email_notification' => true,
                    'voucher_templates' => true,
                    'multi_location' => true,
                    'reseller_module' => true,
                    'advanced_analytics' => true,
                    'white_label' => false,
                    'sla' => false,
                    'dedicated_support' => false,
                    'custom_development' => false,
                    'on_premise' => false,
                    'full_api' => true,
                    'support_type' => '24/7',
                ],
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Paket enterprise untuk ISP besar dengan SLA dan dedicated support.',
                'price_monthly' => 1499000,
                'price_yearly' => 14990000,
                'max_routers' => 100,
                'max_users' => 15000,
                'max_vouchers' => 999999,
                'max_online_users' => 3000,
                'custom_domain' => true,
                'api_access' => true,
                'priority_support' => true,
                'features' => [
                    'basic_radius' => true,
                    'full_radius' => true,
                    'basic_reports' => true,
                    'advanced_reports' => true,
                    'pppoe' => true,
                    'hotspot' => true,
                    'sms_notification' => true,
                    'email_notification' => true,
                    'voucher_templates' => true,
                    'multi_location' => true,
                    'reseller_module' => true,
                    'advanced_analytics' => true,
                    'white_label' => true,
                    'sla' => true,
                    'dedicated_support' => true,
                    'dedicated_account_manager' => true,
                    'custom_development' => false,
                    'on_premise' => false,
                    'full_api' => true,
                    'unlimited_vouchers' => true,
                    'support_type' => 'dedicated_manager',
                ],
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Platinum (Unlimited)',
                'slug' => 'platinum',
                'description' => 'Paket platinum tanpa batas untuk perusahaan besar dengan kebutuhan kustom.',
                'price_monthly' => 2999000,
                'price_yearly' => 29990000,
                'max_routers' => 9999,
                'max_users' => 99999,
                'max_vouchers' => 999999,
                'max_online_users' => 9999,
                'custom_domain' => true,
                'api_access' => true,
                'priority_support' => true,
                'features' => [
                    'basic_radius' => true,
                    'full_radius' => true,
                    'basic_reports' => true,
                    'advanced_reports' => true,
                    'pppoe' => true,
                    'hotspot' => true,
                    'sms_notification' => true,
                    'email_notification' => true,
                    'voucher_templates' => true,
                    'multi_location' => true,
                    'reseller_module' => true,
                    'advanced_analytics' => true,
                    'white_label' => true,
                    'full_white_label' => true,
                    'sla' => true,
                    'dedicated_support' => true,
                    'dedicated_account_manager' => true,
                    'custom_development' => true,
                    'on_premise' => true,
                    'full_api' => true,
                    'custom_api' => true,
                    'unlimited_routers' => true,
                    'unlimited_customers' => true,
                    'unlimited_vouchers' => true,
                    'unlimited_online_users' => true,
                    'support_type' => 'vip',
                ],
                'is_active' => true,
                'sort_order' => 7,
            ],
        ];

        foreach ($plans as $plan) {
            SubscriptionPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }

        $this->command->info('7 subscription plans seeded successfully:');
        $this->command->line('  1. Free (Trial) - Rp 0');
        $this->command->line('  2. Starter - Rp 99.000/bulan');
        $this->command->line('  3. Basic - Rp 199.000/bulan');
        $this->command->line('  4. Professional - Rp 399.000/bulan');
        $this->command->line('  5. Business - Rp 799.000/bulan');
        $this->command->line('  6. Enterprise - Rp 1.499.000/bulan');
        $this->command->line('  7. Platinum (Unlimited) - Rp 2.999.000/bulan');
    }
}
