<?php

namespace App\Services;

use App\Models\Tenant\Nas;
use App\Models\Tenant\ServicePlan;
use App\Models\Tenant\Customer;

class RouterScriptService
{
    protected string $radiusServer;
    protected string $radiusSecret;
    protected int $radiusAuthPort;
    protected int $radiusAcctPort;

    public function __construct()
    {
        $this->radiusServer = config('radius.server', '127.0.0.1');
        $this->radiusSecret = config('radius.secret', 'radiussecret');
        $this->radiusAuthPort = config('radius.auth_port', 1812);
        $this->radiusAcctPort = config('radius.acct_port', 1813);
    }

    public function generateFullScript(Nas $nas, array $options = []): string
    {
        $parts = [];

        $parts[] = $this->generateHeader($nas);
        $parts[] = $this->generateRadiusConfig($nas, $options);
        $parts[] = $this->generatePPPoEServerConfig($nas, $options);
        $parts[] = $this->generateHotspotConfig($nas, $options);
        $parts[] = $this->generateProfilesConfig($options);
        $parts[] = $this->generateFirewallRules($options);
        $parts[] = $this->generateFooter();

        return implode("\n\n", array_filter($parts));
    }

    public function generateHeader(Nas $nas): string
    {
        $date = date('Y-m-d H:i:s');
        return <<<SCRIPT
# ============================================
# MikroTik RouterOS Configuration Script
# Generated by ISP Manager
# Router: {$nas->name} ({$nas->nasname})
# Date: {$date}
# ============================================
# WARNING: Review this script before running!
# This script will modify your router configuration.
# ============================================

SCRIPT;
    }

    public function generateRadiusConfig(Nas $nas, array $options = []): string
    {
        $radiusServer = $options['radius_server'] ?? $this->radiusServer;
        $radiusSecret = $options['radius_secret'] ?? $nas->secret ?? $this->radiusSecret;
        $authPort = $options['auth_port'] ?? $this->radiusAuthPort;
        $acctPort = $options['acct_port'] ?? $this->radiusAcctPort;
        $timeout = $options['timeout'] ?? 3000;

        return <<<SCRIPT
# ============================================
# RADIUS Server Configuration
# ============================================

/radius
add address={$radiusServer} secret="{$radiusSecret}" service=hotspot,ppp,login,wireless \\
    authentication-port={$authPort} accounting-port={$acctPort} timeout={$timeout}ms

/radius incoming
set accept=yes port=3799

SCRIPT;
    }

    public function generatePPPoEServerConfig(Nas $nas, array $options = []): string
    {
        $interface = $options['pppoe_interface'] ?? 'ether1';
        $poolName = $options['pool_name'] ?? 'pppoe-pool';
        $poolRange = $options['pool_range'] ?? '10.10.0.2-10.10.255.254';
        $localAddress = $options['local_address'] ?? '10.10.0.1';
        $dnsServers = $options['dns_servers'] ?? '8.8.8.8,8.8.4.4';

        return <<<SCRIPT
# ============================================
# PPPoE Server Configuration
# ============================================

# Create IP Pool
/ip pool
add name={$poolName} ranges={$poolRange}

# Create PPPoE Profile with RADIUS
/ppp profile
add name=pppoe-radius local-address={$localAddress} remote-address={$poolName} \\
    dns-server={$dnsServers} use-encryption=yes use-compression=no \\
    only-one=yes

# Enable PPPoE Server
/interface pppoe-server server
add interface={$interface} service-name=ISP-Service default-profile=pppoe-radius \\
    authentication=mschap2,mschap1,chap,pap one-session-per-host=yes \\
    max-mtu=1480 max-mru=1480

# PPP Settings for RADIUS
/ppp aaa
set use-radius=yes accounting=yes interim-update=5m

SCRIPT;
    }

    public function generateHotspotConfig(Nas $nas, array $options = []): string
    {
        $interface = $options['hotspot_interface'] ?? 'ether2';
        $network = $options['hotspot_network'] ?? '192.168.100.0/24';
        $gateway = $options['hotspot_gateway'] ?? '192.168.100.1';
        $poolRange = $options['hotspot_pool'] ?? '192.168.100.2-192.168.100.254';
        $dnsName = $options['dns_name'] ?? 'hotspot.local';
        $loginPage = $options['login_page'] ?? '';

        return <<<SCRIPT
# ============================================
# Hotspot Configuration
# ============================================

# Set IP Address on Hotspot Interface
/ip address
add address={$gateway}/24 interface={$interface} comment="Hotspot Gateway"

# Create Hotspot IP Pool
/ip pool
add name=hotspot-pool ranges={$poolRange}

# Create DHCP Server for Hotspot
/ip dhcp-server
add name=hotspot-dhcp interface={$interface} address-pool=hotspot-pool disabled=no

/ip dhcp-server network
add address={$network} gateway={$gateway} dns-server={$gateway}

# Create Hotspot Profile with RADIUS
/ip hotspot profile
add name=hsprof-radius hotspot-address={$gateway} dns-name={$dnsName} \\
    html-directory=hotspot use-radius=yes radius-accounting=yes \\
    login-by=http-chap,http-pap,cookie,mac-cookie nas-port-type=wireless-802.11

# Enable Hotspot Server
/ip hotspot
add name=hotspot-server interface={$interface} address-pool=hotspot-pool \\
    profile=hsprof-radius idle-timeout=5m keepalive-timeout=2m disabled=no

# Hotspot User Profile
/ip hotspot user profile
add name=default rate-limit="" shared-users=1 status-autorefresh=1m \\
    transparent-proxy=no

SCRIPT;
    }

    public function generateProfilesConfig(array $options = []): string
    {
        $servicePlans = ServicePlan::where('is_active', true)->get();
        
        if ($servicePlans->isEmpty()) {
            return "# No service plans configured\n";
        }

        $script = <<<SCRIPT
# ============================================
# Service Plan Profiles (Queue)
# ============================================

/queue type
add name=pcq-download-default kind=pcq pcq-classifier=dst-address pcq-rate=0
add name=pcq-upload-default kind=pcq pcq-classifier=src-address pcq-rate=0

/queue simple

SCRIPT;

        foreach ($servicePlans as $plan) {
            $name = $this->sanitizeName($plan->name);
            $maxLimit = ($plan->bandwidth_up ?? '1M') . '/' . ($plan->bandwidth_down ?? '1M');
            
            $script .= "# Profile: {$plan->name}\n";
            $script .= "# add name=\"{$name}\" target=\"\" max-limit={$maxLimit} comment=\"{$plan->code}\"\n";
        }

        return $script;
    }

    public function generateFirewallRules(array $options = []): string
    {
        $wanInterface = $options['wan_interface'] ?? 'ether1-WAN';

        return <<<SCRIPT
# ============================================
# Basic Firewall & NAT Rules
# ============================================

/ip firewall nat
add chain=srcnat out-interface={$wanInterface} action=masquerade comment="NAT for Internet Access"

/ip firewall filter
# Allow established and related connections
add chain=input connection-state=established,related action=accept comment="Accept established"
add chain=forward connection-state=established,related action=accept

# Drop invalid connections
add chain=input connection-state=invalid action=drop comment="Drop invalid"
add chain=forward connection-state=invalid action=drop

# Allow RADIUS (optional - if RADIUS server needs access)
add chain=input protocol=udp dst-port=1812-1813 action=accept comment="Allow RADIUS"
add chain=input protocol=udp dst-port=3799 action=accept comment="Allow RADIUS COA"

# Allow Winbox, SSH, Web
add chain=input protocol=tcp dst-port=8291 action=accept comment="Allow Winbox"
add chain=input protocol=tcp dst-port=22 action=accept comment="Allow SSH"
add chain=input protocol=tcp dst-port=80,443 action=accept comment="Allow HTTP/HTTPS"

# Allow ICMP
add chain=input protocol=icmp action=accept comment="Allow Ping"

# Drop all other input
add chain=input action=drop comment="Drop all other input"

SCRIPT;
    }

    public function generateFooter(): string
    {
        return <<<SCRIPT
# ============================================
# End of Configuration Script
# ============================================
# Remember to:
# 1. Backup your current configuration before applying
# 2. Review and modify IP addresses as needed
# 3. Test RADIUS connectivity after applying
# 4. Configure login page for Hotspot if needed
# ============================================

SCRIPT;
    }

    public function generateCustomerScript(Customer $customer): string
    {
        if (!$customer->servicePlan) {
            return "# Error: Customer has no service plan assigned\n";
        }

        $plan = $customer->servicePlan;
        $username = $customer->username;
        $password = $customer->pppoe_password ?? 'password123';
        $profile = $this->sanitizeName($plan->name);
        $maxLimit = ($plan->bandwidth_up ?? '1M') . '/' . ($plan->bandwidth_down ?? '1M');

        $script = <<<SCRIPT
# ============================================
# Customer: {$customer->name}
# Username: {$username}
# Package: {$plan->name}
# ============================================

SCRIPT;

        if ($customer->service_type === 'pppoe') {
            $script .= <<<SCRIPT
# PPPoE Secret
/ppp secret
add name="{$username}" password="{$password}" service=pppoe profile=pppoe-radius \\
    comment="{$customer->name} - {$plan->name}"

SCRIPT;
        } else {
            $script .= <<<SCRIPT
# Hotspot User
/ip hotspot user
add name="{$username}" password="{$password}" profile=default \\
    limit-uptime="{$this->formatValidity($plan)}" \\
    comment="{$customer->name} - {$plan->name}"

SCRIPT;
        }

        if ($customer->static_ip) {
            $script .= <<<SCRIPT

# Static IP Assignment
# Note: Configure static IP in RADIUS or PPP secret remote-address

SCRIPT;
        }

        return $script;
    }

    public function generateNasRegistration(Nas $nas): string
    {
        return <<<SCRIPT
# ============================================
# NAS Registration for FreeRADIUS
# Add this to /etc/freeradius/3.0/clients.conf
# ============================================

client {$nas->shortname} {
    ipaddr = {$nas->nasname}
    secret = {$nas->secret}
    shortname = {$nas->shortname}
    nastype = other
    # For MikroTik, you can also use:
    # nastype = mikrotik
}

SCRIPT;
    }

    public function generateBulkCustomerScript(array $customers): string
    {
        $script = "# Bulk Customer Import Script\n";
        $script .= "# Generated: " . date('Y-m-d H:i:s') . "\n\n";

        foreach ($customers as $customer) {
            if ($customer instanceof Customer) {
                $script .= $this->generateCustomerScript($customer) . "\n";
            }
        }

        return $script;
    }

    protected function sanitizeName(string $name): string
    {
        $name = preg_replace('/[^a-zA-Z0-9\-_]/', '-', $name);
        $name = preg_replace('/-+/', '-', $name);
        return trim($name, '-');
    }

    protected function formatValidity(ServicePlan $plan): string
    {
        $value = $plan->validity ?? 30;
        $unit = $plan->validity_unit ?? 'days';

        $formats = [
            'minutes' => $value . 'm',
            'hours' => $value . 'h',
            'days' => $value . 'd',
            'months' => ($value * 30) . 'd',
        ];

        return $formats[$unit] ?? $value . 'd';
    }
}
